### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by balasankarc** [fog/fog-xenserver#54]
I tried `$bundle exec rake` and got this output. Can you help me find out what the issue is?

```
$ bundle exec rake
/usr/bin/ruby2.1 -I"lib:spec" -I"/var/lib/gems/2.1.0/gems/rake-10.4.2/lib" "/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "spec/fog/compute/xen_server/models/blob_spec.rb" "spec/fog/compute/xen_server/models/blobs_spec.rb" "spec/fog/compute/xen_server/models/bond_spec.rb" "spec/fog/compute/xen_server/models/bonds_spec.rb" "spec/fog/compute/xen_server/models/console_spec.rb" "spec/fog/compute/xen_server/models/consoles_spec.rb" "spec/fog/compute/xen_server/models/crash_dump_spec.rb" "spec/fog/compute/xen_server/models/crash_dumps_spec.rb" "spec/fog/compute/xen_server/models/dr_task_spec.rb" "spec/fog/compute/xen_server/models/dr_tasks_spec.rb" "spec/fog/compute/xen_server/models/gpu_group_spec.rb" "spec/fog/compute/xen_server/models/gpu_groups_spec.rb" "spec/fog/compute/xen_server/models/guest_metrics_spec.rb" "spec/fog/compute/xen_server/models/guests_metrics_spec.rb" "spec/fog/compute/xen_server/models/host_cpu_spec.rb" "spec/fog/compute/xen_server/models/host_cpus_spec.rb" "spec/fog/compute/xen_server/models/host_crash_dump_spec.rb" "spec/fog/compute/xen_server/models/host_crash_dumps_spec.rb" "spec/fog/compute/xen_server/models/host_metrics_spec.rb" "spec/fog/compute/xen_server/models/host_patch_spec.rb" "spec/fog/compute/xen_server/models/host_patchs_spec.rb" "spec/fog/compute/xen_server/models/host_spec.rb" "spec/fog/compute/xen_server/models/hosts_metrics_spec.rb" "spec/fog/compute/xen_server/models/hosts_spec.rb" "spec/fog/compute/xen_server/models/network_spec.rb" "spec/fog/compute/xen_server/models/networks_spec.rb" "spec/fog/compute/xen_server/models/pbd_spec.rb" "spec/fog/compute/xen_server/models/pbds_spec.rb" "spec/fog/compute/xen_server/models/pci_spec.rb" "spec/fog/compute/xen_server/models/pcis_spec.rb" "spec/fog/compute/xen_server/models/pgpu_spec.rb" "spec/fog/compute/xen_server/models/pgpus_spec.rb" "spec/fog/compute/xen_server/models/pif_metrics_spec.rb" "spec/fog/compute/xen_server/models/pif_spec.rb" "spec/fog/compute/xen_server/models/pifs_metrics_spec.rb" "spec/fog/compute/xen_server/models/pifs_spec.rb" "spec/fog/compute/xen_server/models/pool_patch_spec.rb" "spec/fog/compute/xen_server/models/pool_patchs_spec.rb" "spec/fog/compute/xen_server/models/pool_spec.rb" "spec/fog/compute/xen_server/models/pools_spec.rb" "spec/fog/compute/xen_server/models/role_spec.rb" "spec/fog/compute/xen_server/models/roles_spec.rb" "spec/fog/compute/xen_server/models/server_appliance_spec.rb" "spec/fog/compute/xen_server/models/server_appliances_spec.rb" "spec/fog/compute/xen_server/models/server_metrics_spec.rb" "spec/fog/compute/xen_server/models/server_spec.rb" "spec/fog/compute/xen_server/models/servers_metrics_spec.rb" "spec/fog/compute/xen_server/models/servers_spec.rb" "spec/fog/compute/xen_server/models/storage_manager_spec.rb" "spec/fog/compute/xen_server/models/storage_managers_spec.rb" "spec/fog/compute/xen_server/models/storage_repositories_spec.rb" "spec/fog/compute/xen_server/models/storage_repository_spec.rb" "spec/fog/compute/xen_server/models/tunnel_spec.rb" "spec/fog/compute/xen_server/models/tunnels_spec.rb" "spec/fog/compute/xen_server/models/vbd_metrics_spec.rb" "spec/fog/compute/xen_server/models/vbd_spec.rb" "spec/fog/compute/xen_server/models/vbds_metrics_spec.rb" "spec/fog/compute/xen_server/models/vbds_spec.rb" "spec/fog/compute/xen_server/models/vdi_spec.rb" "spec/fog/compute/xen_server/models/vdis_spec.rb" "spec/fog/compute/xen_server/models/vif_metrics_spec.rb" "spec/fog/compute/xen_server/models/vif_spec.rb" "spec/fog/compute/xen_server/models/vifs_metrics_spec.rb" "spec/fog/compute/xen_server/models/vifs_spec.rb" "spec/fog/compute/xen_server/models/vlan_spec.rb" "spec/fog/compute/xen_server/models/vlans_spec.rb" "spec/fog/compute/xen_server/models/vmpp_spec.rb" "spec/fog/compute/xen_server/models/vmpps_spec.rb" "spec/fog/compute/xen_server/models/vtpm_spec.rb" "spec/fog/compute/xen_server/models/vtpms_spec.rb" "spec/fog/compute/xen_server/requests/builtin_templates_spec.rb" "spec/fog/compute/xen_server/requests/clone_server_spec.rb" "spec/fog/compute/xen_server/requests/create_network_spec.rb" "spec/fog/compute/xen_server/requests/create_server_spec.rb" "spec/fog/compute/xen_server/requests/create_vbd_spec.rb" "spec/fog/compute/xen_server/requests/create_vdi_spec.rb" "spec/fog/compute/xen_server/requests/create_vif_spec.rb" "spec/fog/compute/xen_server/requests/sync_database_pool_spec.rb" "spec/fog/compute/xen_server_spec.rb" 
/var/lib/gems/2.1.0/gems/turn-0.9.7/lib/turn/minitest.rb:22:in `<top (required)>': MiniTest v5.8.0 is out of date. (RuntimeError)
Please update to a newer version, but version 5.0.0 or above will not work. .
	from /var/lib/gems/2.1.0/gems/turn-0.9.7/lib/turn.rb:13:in `require'
	from /var/lib/gems/2.1.0/gems/turn-0.9.7/lib/turn.rb:13:in `<top (required)>'
	from /home/balasankarc/git/fog-xenserver/spec/minitest_helper.rb:3:in `require'
	from /home/balasankarc/git/fog-xenserver/spec/minitest_helper.rb:3:in `<top (required)>'
	from /home/balasankarc/git/fog-xenserver/spec/fog/compute/xen_server/models/blob_spec.rb:1:in `require'
	from /home/balasankarc/git/fog-xenserver/spec/fog/compute/xen_server/models/blob_spec.rb:1:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `require'
	from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
	from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
	from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:spec" -I"/var/lib/gems/2.1.0/gems/rake-10.4.2/lib" "/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "spec/fog/compute/xen_server/models/blob_spec.rb" "spec/fog/compute/xen_server/models/blobs_spec.rb" "spec/fog/compute/xen_server/models/bond_spec.rb" "spec/fog/compute/xen_server/models/bonds_spec.rb" "spec/fog/compute/xen_server/models/console_spec.rb" "spec/fog/compute/xen_server/models/consoles_spec.rb" "spec/fog/compute/xen_server/models/crash_dump_spec.rb" "spec/fog/compute/xen_server/models/crash_dumps_spec.rb" "spec/fog/compute/xen_server/models/dr_task_spec.rb" "spec/fog/compute/xen_server/models/dr_tasks_spec.rb" "spec/fog/compute/xen_server/models/gpu_group_spec.rb" "spec/fog/compute/xen_server/models/gpu_groups_spec.rb" "spec/fog/compute/xen_server/models/guest_metrics_spec.rb" "spec/fog/compute/xen_server/models/guests_metrics_spec.rb" "spec/fog/compute/xen_server/models/host_cpu_spec.rb" "spec/fog/compute/xen_server/models/host_cpus_spec.rb" "spec/fog/compute/xen_server/models/host_crash_dump_spec.rb" "spec/fog/compute/xen_server/models/host_crash_dumps_spec.rb" "spec/fog/compute/xen_server/models/host_metrics_spec.rb" "spec/fog/compute/xen_server/models/host_patch_spec.rb" "spec/fog/compute/xen_server/models/host_patchs_spec.rb" "spec/fog/compute/xen_server/models/host_spec.rb" "spec/fog/compute/xen_server/models/hosts_metrics_spec.rb" "spec/fog/compute/xen_server/models/hosts_spec.rb" "spec/fog/compute/xen_server/models/network_spec.rb" "spec/fog/compute/xen_server/models/networks_spec.rb" "spec/fog/compute/xen_server/models/pbd_spec.rb" "spec/fog/compute/xen_server/models/pbds_spec.rb" "spec/fog/compute/xen_server/models/pci_spec.rb" "spec/fog/compute/xen_server/models/pcis_spec.rb" "spec/fog/compute/xen_server/models/pgpu_spec.rb" "spec/fog/compute/xen_server/models/pgpus_spec.rb" "spec/fog/compute/xen_server/models/pif_metrics_spec.rb" "spec/fog/compute/xen_server/models/pif_spec.rb" "spec/fog/compute/xen_server/models/pifs_metrics_spec.rb" "spec/fog/compute/xen_server/models/pifs_spec.rb" "spec/fog/compute/xen_server/models/pool_patch_spec.rb" "spec/fog/compute/xen_server/models/pool_patchs_spec.rb" "spec/fog/compute/xen_server/models/pool_spec.rb" "spec/fog/compute/xen_server/models/pools_spec.rb" "spec/fog/compute/xen_server/models/role_spec.rb" "spec/fog/compute/xen_server/models/roles_spec.rb" "spec/fog/compute/xen_server/models/server_appliance_spec.rb" "spec/fog/compute/xen_server/models/server_appliances_spec.rb" "spec/fog/compute/xen_server/models/server_metrics_spec.rb" "spec/fog/compute/xen_server/models/server_spec.rb" "spec/fog/compute/xen_server/models/servers_metrics_spec.rb" "spec/fog/compute/xen_server/models/servers_spec.rb" "spec/fog/compute/xen_server/models/storage_manager_spec.rb" "spec/fog/compute/xen_server/models/storage_managers_spec.rb" "spec/fog/compute/xen_server/models/storage_repositories_spec.rb" "spec/fog/compute/xen_server/models/storage_repository_spec.rb" "spec/fog/compute/xen_server/models/tunnel_spec.rb" "spec/fog/compute/xen_server/models/tunnels_spec.rb" "spec/fog/compute/xen_server/models/vbd_metrics_spec.rb" "spec/fog/compute/xen_server/models/vbd_spec.rb" "spec/fog/compute/xen_server/models/vbds_metrics_spec.rb" "spec/fog/compute/xen_server/models/vbds_spec.rb" "spec/fog/compute/xen_server/models/vdi_spec.rb" "spec/fog/compute/xen_server/models/vdis_spec.rb" "spec/fog/compute/xen_server/models/vif_metrics_spec.rb" "spec/fog/compute/xen_server/models/vif_spec.rb" "spec/fog/compute/xen_server/models/vifs_metrics_spec.rb" "spec/fog/compute/xen_server/models/vifs_spec.rb" "spec/fog/compute/xen_server/models/vlan_spec.rb" "spec/fog/compute/xen_server/models/vlans_spec.rb" "spec/fog/compute/xen_server/models/vmpp_spec.rb" "spec/fog/compute/xen_server/models/vmpps_spec.rb" "spec/fog/compute/xen_server/models/vtpm_spec.rb" "spec/fog/compute/xen_server/models/vtpms_spec.rb" "spec/fog/compute/xen_server/requests/builtin_templates_spec.rb" "spec/fog/compute/xen_server/requests/clone_server_spec.rb" "spec/fog/compute/xen_server/requests/create_network_spec.rb" "spec/fog/compute/xen_server/requests/create_server_spec.rb" "spec/fog/compute/xen_server/requests/create_vbd_spec.rb" "spec/fog/compute/xen_server/requests/create_vdi_spec.rb" "spec/fog/compute/xen_server/requests/create_vif_spec.rb" "spec/fog/compute/xen_server/requests/sync_database_pool_spec.rb" "spec/fog/compute/xen_server_spec.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)

```

**Comment by fernandes** [comment]
hi @balasankarc , this is weird (this warning about minitest)

as you can check on https://travis-ci.org/fog/fog-xenserver/jobs/58320013#L146 the build is running fine on my machine and CI, have you updated the gems (Gemfile.lock)?

**Comment by balasankarc** [comment]
@fernandes 
No. I cloned the repo, ran `bundle install` and then `bundle exec rake`. See the termcast (you can use the command `asciicast play` to run it) https://asciinema.org/a/5m6aw7lnrl2n5twuai2pim111

**Comment by plribeiro3000** [comment]
@balasankarc As @fernandes suggested, everything is running fine. I suspect the issue might be on your enviroment. Why did you use the system ruby?

**Comment by balasankarc** [comment]
@plribeiro3000 

No specific reason. I usually use system ruby (Ruby 2.2.0) for all general purpose stuff. So, you think it is an issue with Ruby version?  Coz, it wouldn't be a problem with gems as I was using bundler.

**Comment by balasankarc** [comment]
Strike that. I removed all other ruby versions except Ruby 2.2.0 and now the tests are running fine.

**Comment by fernandes** [comment]
glad to hear @balasankarc ! :smile:

**Comment by plribeiro3000** [comment]
Awesome. Thank you for The feedback @balasankarc!

Em qui, 14 de jan de 2016 07:11, Celso Fernandes <notifications@github.com>
escreveu:
